CREATE TABLE departments
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    parent_id INT REFERENCES departments (id),
    creation_date DATE NOT NULL,
    termination_date DATE
);

CREATE TABLE employees
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    second_name VARCHAR(255) NOT NULL,
    patronymic VARCHAR(255) NOT NULL,
    hire_date DATE,
    termination_date DATE,
    department_id INT REFERENCES departments (id)
);

CREATE TABLE transfer_history
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   INT  NOT NULL REFERENCES employees (id),
    department_from INT REFERENCES departments (id),
    department_to INT REFERENCES departments (id),
    transfer_date DATE NOT NULL
);
